# Generated by Django 2.2.3 on 2019-10-07 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gonderi',
            name='cover',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
