# Generated by Django 2.2.3 on 2019-09-27 17:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IletisimMod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Adı', models.CharField(max_length=200)),
                ('Soyadı', models.CharField(max_length=200)),
                ('E_Posta', models.EmailField(max_length=200)),
                ('Mesaj', models.TextField()),
                ('Zaman', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
